### ISSUE TITLE
Extracting inline images from MMS

### ISSUE THREAD

**Issue by christhesoul** [thoughtbot/griddler#104]
Hey

Thanks for all your hard work on Griddler.

I've got it working nicely with emails and "proper" attachments, but I'm trying to get it to work with MMS messages sent to an email address.

Using pry, I can see that MMS messages have inline images that are base64 encoded in the raw_body of the params.

Has anybody got any suggestions as to how I can try to extract this encoded image and convert it to a "real" image file, that I can associate with an object in my app?

Not sure if this question belongs here or it's more for StackOverflow. Just looking for some pointers really.

Thank you
Chris

**Comment by TanookiMario** [comment]
Hi! I just came across this issue. I am trying to send inline attachments with griddler/mandrill for a Rails app. Whenever it gets processed the attachments have incorrect names. I inspected the `raw_text` of the email and noticed this:

`<img src="cid:1620c85e6d0d0b594a91" alt="Yzma_(2)_(2)_(1)_(3)_(2)_(1).jpg" class="" style="max-width: 100%;">`

it seems like the `ActionDispatch::Http::UploadedFile` created by rails is using the `cid` from the img tag as the filename, instead of the `alt`, which is the actual file name. Is there a reason the actual name of the uploaded file is not being used for the `cid`? How is the `cid` being made?

Any info would help! thanks!
