### ISSUE TITLE
Access to params

### ISSUE THREAD

**Issue by marine44** [thoughtbot/griddler#139]
Is there a way to access the params from the original HTTP post from mailgun?

I want to access params[:timestamp], params[:token] and params[:signature] to allow me to verify the web hooks.

See "Securing Webhooks" at http://documentation.mailgun.com/user_manual.html#webhooks

**Comment by dmarkow** [comment]
Unfortunately, the way Rails 4 (and I think 3?) isolate Engines, you can't just re-open the controller. I just tried the recommendations above and it results in:

```
AbstractController::ActionNotFound (The action 'create' could not be found for Griddler::EmailsController):
```

It appears that because I have now defined `Griddler::EmailsController` in my own app, the one from the griddler gem is never used/loaded. 

What worked for me was inheriting

```ruby
# in config/routes.rb
post '/incoming_email' => 'griddler/custom_emails#create'

# in app/controllers/griddler/custom_emails_controller.rb
class Griddler::CustomEmailsController < Griddler::EmailsController
  before_action :foo

  private
  def foo
    # do something
  end
end
```

However, while this is a good way to deal with authentication, it still doesn't provide my email processor class with access to the full set of original params. For example, with Mailgun, they post additional things like their own version of the stripped out body and signature (vs. letting griddler do this). It would be nice to have access to all of those params just in case.

Is there any reason/potential downside to just making the `attr_reader :params` line public?

**Comment by gabebw** [comment]
@dmarkow I'm confused - since it's a subclass, `normalized_params` is still available to you, right? And since it's a controller, isn't `params` available as well?

**Comment by dmarkow** [comment]
Yes, `params` is available in my custom controller, but I need it in my `EmailProcessor` class, not the controller.

It feels to me that the `Griddler::Email` class should expose the params it was based off, especially considering that only some of the original params are being mapped to attributes. But for my purposes, overriding the `process_email(email)` method so I can send a second parameter to my `EmailProcessor` class seems to work:

```ruby
def process_email(email)
  EmailProcessor.new(email, params).process
end
```
