### ISSUE TITLE
Why params are private?

### ISSUE THREAD

**Issue by jniechcial** [thoughtbot/griddler#227]
I see that `params` are private for Griddler::Email class. There were also couple of PRs for `griddler-mandrill` gem regarding `email` key in `params` that are e.g. adding it to CC when `to` is empty, etc. However, it's not matching my requirements - I don't want to fill any of the email `to`, `cc` or `bcc` fields with that value, I just need it to make some other processing. If `params` were accessible, I could do it easily but right now I can't. Is there any reason that this hash is private?

**Comment by wingrunr21** [comment]
I believe `params` is private because it is the output of calling `normalize_params` from the various adapters. The `Griddler::Email` class is taking those params and exposing them in a common interface.

If you only need the `params` themselves, you have a few options:

1. Use `send`
2. Use `instance_variable_get`
3. Use your own controller endpoint. Call `normalize_params` like [`Griddler::EmailsController` does](https://github.com/thoughtbot/griddler/blob/master/app/controllers/griddler/emails_controller.rb) and then process those raw normalized params as you see fit

I do not think marking `params` as public is the right choice going forward though.
