### ISSUE TITLE
How to parse the recipient  address?

### ISSUE THREAD

**Issue by shakycode** [thoughtbot/griddler#253]
This may be a stack question but the docs are not super clear for me so far.

I've setup griddler with sendgrid and the griddler-sendgrid adapter.  I have an initializer and a class which processes the email.  Right now all I'm trying to do is log the `from` address, `body`, `subject`, and `to` address.  

Here's what my code looks like:

**email_processor.rb**
````
class EmailProcessor
  def initialize(email)
    @email = email
  end

  def process
    log_dir = '/Users/shakycode/Dropbox/burnonce'
    log = Logger.new("#{log_dir}/griddler#{Time.now.strftime("%m-%d-%Y")}.log")
    log.info "body: #{@email.body} from: #{@email.from[:email]} to: #{@email.to} subject: #{@email.subject}"
  end
end
````

This works and logs, but for the to address I can't figure out how to pull it out.  As I will be taking the inbound `to` address and looking it up against users eventually for a match.  I just need to know how to pull the to: address out of the params/hash.

Here's the output in my log with this method being in place.

````
I, [2016-03-27T10:19:14.982890 #56835]  INFO -- : body: hi from: shakycode@me.com to: [{:token=>"test", :host=>"burnonce.com", :email=>"test@burnonce.com", :full=>"test@burnonce.com", :name=>nil}] subject: h
````

When I call `@email.to` I assumed this to be a convenience method that gives me the destination address i.e. `test!@burnonce.com`.  Do I need to somehow parse this further to get the `to` email address?

Sorry if this is not a real issue but I've been banging my head for a good hour figuring this out.

It should be noted that I'm testing this in development with Sendgrid posting to an ngrok URL that opens up my rails app.  I'm also on Rails 4.2.6 and Ruby 2.3.0 in case this helps at all.

**Comment by wingrunr21** [comment]
Hi,

No problem at all. Let's take a look at this:

You are correct that `@email.to` is a convenience method for getting where the email was sent. Looking at your log output, you can see that `@email.to` is being printed as:

```ruby
[{:token=>"test", :host=>"burnonce.com", :email=>"test@burnonce.com", :full=>"test@burnonce.com", :name=>nil}]
```

This is an array of hashes where each hash is detailing what Griddler parsed from the incoming data about the email. In fact, the hashes in this array are of the same structure as the `from` hash (which you have used to extract the from address via the `@email.from[:email]` call).

One thing to remember is that an email can be addressed to multiple recipients. That is why `@email.to` returns an array. So, in order to get the To address here, you can call `@email.to.first[:email]`. If you need to log every To address in the email, you just need to _collect_ the `:email` from each hash in the array.

**Comment by shakycode** [comment]
@wingrunr21 Thank you so much for the quick response.  In my half-asleep state I was overlooking the array of hashes.  Next time I should have another cup of coffee before opening issues.  I refactored the class to look like this.

````
class EmailProcessor
  def initialize(email)
    @to = email.to.first[:email]
    @from = email.from[:email]
    @body = email.body
    @subject = email.subject
  end

  def process
    log_dir = '/Users/shakycode/Dropbox/burnonce'
    log = Logger.new("#{log_dir}/griddler#{Time.now.strftime("%m-%d-%Y")}.log")
    log.info "body: #{@body} from: #{@from} to: #{@to} subject: #{@subject}"
  end
end
````
And now the log output looks like this:

````
I, [2016-03-27T10:51:37.861107 #57436]  INFO -- : body: hi from: shakycode@me.com to: john@burnonce.com subject: hi
````

Problem solved, again thanks so much for the help and for writing such a great gem.  It definitely came in handy.  I will continue looking at the docs to see what else I can do with this, but so far everything is working as expected.  Appreciate the clarification.

Cheers!
