### ISSUE TITLE
Using griddler with delayed jobs

### ISSUE THREAD

**Issue by echan00** [thoughtbot/griddler#261]
I'm trying to use delayed_jobs (background workers) to process my incoming email. 

```
class EmailProcessor

  def initialize(email)
  	@raw_html = email.raw_html
  	@subject = email.subject
  end

  def process
  	do something with @raw_html & @subject
  end
  handle_asynchronously :process, :priority => 20

end
```

The problem is I can't pass instance variables (@raw_html & @subject) into delayed jobs. Delayed jobs requests that I save data into the model to be retrieved in the background task, but I would prefer to have a background worker complete the entire task (including saving the record). 

Any thoughts?

**Comment by wingrunr21** [comment]
Hmm, well I think you'll have to persist the data in some way so that delayed_job can pull it back out. I've got a few ideas:

* Use a fast, persistent cache of some type if you do not want to write to the database. You can use the email's ID as your key.
* Create a very light weight model. Call it `UnprocessedEmail` or something. The idea would be to persist incoming emails as quickly as possible.
* Use a lightweight background processor to do the initial persist (like [`sucker_punch`](https://github.com/brandonhilkert/sucker_punch) and then have delayed_job do the heavy lifting
* Use `sucker_punch` to do the entire processing of the email

You could also just spawn a thread to do the job of sucker_punch if you don't want to pull in all the dependencies (although obviously then you have to manage the thread-safety aspects).

**Comment by echan00** [comment]
Thanks @wingrunr21, all great ideas. Will try them!
